


baseurl = "https://liripo.github.io"
Paginate = 10
# Rewrite URLs to be relative to the current content.
relativeurls = true
#添加中文计数
hasCJKLanguage = true 

# Default is "public", but if you're using GitHub pages you
# need to point this to "docs".
publishDir = "docs"
# additional settings
languageCode = "Zh-cn"
copyright = "Liripo"
googleAnalytics = "UA-155993181-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
# These settings specify the title for your site, and the name of
# the Hugo theme that it uses.
title = "Liripo"
theme = "github-style"

[params]
  author = "Liripo"
  description = "Liripo's blog by blogdown!"
  github = "Liripo"
#  misskey = "user profile url"
#  mastodon = "user profile url"
  email = "liripo@qq.com"
  utterances = "liripo/liripo.github.io"
  avatar = "https://liripo.github.io/image/caomao.jpg"
  url = "https://github.com/Liripo"
#  keywords = "blog, google analytics"
[markup.goldmark.renderer]
    unsafe = true
[markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
[outputs]
    home = ["HTML", "RSS", "JSON"]
#----------my own 
