
# The config file is written using TOML, which stands for "Tom's Obvious,
# Minimal Language". See: https://github.com/toml-lang/toml

# The URL for your website. It should end with a trailing slash,
# e.g. "https://example.com/". If you're planning to deploy on
# GitHub pages the way I've done for the example site at
# https://djnavarro.github.io/hugo-calade/, then you can do something
# like this:
#
#    baseurl = "/hugo-calade/"
#
baseurl = "https://liripo.github.io"
Paginate = 10
# Rewrite URLs to be relative to the current content.
relativeurls = true
#添加中文计数
hasCJKLanguage = true 

# Default is "public", but if you're using GitHub pages you
# need to point this to "docs".
publishDir = "docs"
# additional settings
languageCode = "Zh-cn"
copyright = "Liripo"
googleAnalytics = "UA-155993181-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
# These settings specify the title for your site, and the name of
# the Hugo theme that it uses.
title = "Liripo"
theme = "github-style"

# What format should the permalinks take?
#[permalinks]
#    post = "/post/:slug/"
#    project = "/project/:slug/"
#
# Alternative version:
#   post = "/post/:year/:month/:day/:slug/"
#   project = "/project/:year/:month/:day/:slug/"


# These settings are used to specify the links in the main
# navigation bar. Each item has a "name" (the link text), a
# "url" (path to the page), and a "weight" (the order).
# Something to keep in mind for new users: you won't find
# specific files that correspond to all of these pages. See
# the documentation for an explanation of where they come from
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3
#[[menu.main]]
#    name = "Projects"
#    url = "/project/"
#    weight = 4
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4



# Parameters used throughout the site.
#
# - "siteHeader":   banner image at the top of the page
# - "siteProfile":  profile image centered within the banner
# - "description":  description of the site
# - "footer":       content of the page footer
# - "twitterImage": image to include within a twitter card
# - "colorPage":    default page background color
# - "colorText":    default text color for the page
# - "colorFade":    default color to use when 'faded' text is needed
# - "colorAccent1": default value for the first accent color (the "highlight")
# - "colorAccent2": default value for the second accent color (the "lowlight")

#[params]
#    siteHeader = "header/banner.png"
#    siteProfile = "header/profile.png"
#    description = "A website of one's own"
#    footer = ""
#    colorPage = "#333333"    # background colour
#    colorText = "#dddddd"    # main text colour
#    colorFade = "#888888"    # faded text colour
#    colorAccent1 = "#6BB0DF" #"#ff69b4" # first accent colour ("highlight")
#    colorAccent2 = "#ba68c8" # second accent colour ("lowlight")
[params]
  author = "liripo"
  description = "Liripo's blog by blogdown!"
  github = "Liripo"
#  misskey = "user profile url"
#  mastodon = "user profile url"
  email = "liripo@qq.com"
  utterances = "liripo/liripo.github.io"
  avatar = "https://themes.gohugo.io/theme/github-style/images/avatar.png"
  url = "https://github.com/Liripo"
#  keywords = "blog, google analytics"
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
[outputs]
    home = ["HTML", "RSS", "JSON"]
#----------my own 
